seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 64
  dropout: 0.3
  num_layers: 4
  norm: layer
  residual: false
  T_0: null
  imp_type: group
  isomorphic: false
  lr: 0.000606
  prune_T_0: 60.0
  prune_lr: 0.000226
  prune_scheduler: true
  prune_step: 2
  prune_warmup: 0.15
  prune_weight_decay: 0.0013
  pruner_type: group
  scheduler: false
  warmup: 0.05
  weight_decay: 5.4e-05
  feat_loss: cwd
  reset: false
  temperature: 5.0
  prune_rate: 0.5
  momentum: 0.99
  kd_lr: 0.00856
  kd_weight_decay: 1.23e-05
  lamb: 0.0
  alpha: 4.0
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.25

gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 512
  norm: layer
  num_layers: 3
  residual: false
  T_0: 90.0
  imp_type: fpgm
  isomorphic: true
  lr: 0.000462
  prune_T_0: 60.0
  prune_lr: 0.00307
  prune_scheduler: true
  prune_step: 1
  prune_warmup: 0.1
  prune_weight_decay: 0.096
  pruner_type: base
  scheduler: true
  warmup: 0.15
  weight_decay: 5.45e-05
  feat_loss: mse
  reset: false
  temperature: null
  prune_rate: 0.7
  momentum: 0.9
  kd_lr: 0.00104
  kd_weight_decay: 3.12e-05
  lamb: 0.0
  alpha: 3.25
  kd_warmup: 0.0
  kd_scheduler: true
  kd_T_0: 30.0
  label_smoothing: 0.25
