seed: 42
dataset:
  split: fixed
sage:
  epochs: 1500
  hidden: 512
  dropout: 0.5
  num_layers: 2
  norm: layer
  residual: true
  T_0: null
  imp_type: lamp
  isomorphic: false
  lr: 0.00306
  prune_T_0: 30.0
  prune_lr: 0.000542
  prune_scheduler: true
  prune_step: 3.0
  prune_warmup: 0.0
  prune_weight_decay: 0.000506
  pruner_type: group
  scheduler: false
  warmup: 0.1
  weight_decay: 2.94e-05
  feat_loss: cwd
  reset: false
  temperature: 0.75
  prune_rate: 0.5
  momentum: 0.99
  kd_lr: 1.76e-05
  kd_weight_decay: 0.000125
  lamb: 1.45
  alpha: 0.05
  kd_warmup: 0.15
  kd_scheduler: true
  kd_T_0: 60.0
  label_smoothing: 0.25

gcn:
  dropout: 0.3
  epochs: 1500
  hidden: 512
  norm: layer
  num_layers: 2
  residual: true
  T_0: 90.0
  imp_type: group
  isomorphic: true
  lr: 0.00364
  prune_T_0: 120.0
  prune_lr: 0.000141
  prune_scheduler: true
  prune_step: 2.0
  prune_warmup: 0.0
  prune_weight_decay: 0.863
  pruner_type: base
  scheduler: true
  warmup: 0.15
  weight_decay: 0.000462
  feat_loss: cwd
  reset: true
  temperature: 1.0
  prune_rate: 0.7
  momentum: 0.995
  kd_lr: 0.000502
  kd_weight_decay: 0.000461
  lamb: 1.9
  alpha: 0.05
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.3
