seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 64
  dropout: 0.2
  num_layers: 6
  norm: layer
  residual: true
  T_0: 30.0
  imp_type: lamp
  isomorphic: false
  lr: 0.000194
  prune_T_0: 30.0
  prune_lr: 0.00232
  prune_scheduler: true
  prune_step: 1
  prune_warmup: 0.15
  prune_weight_decay: 1.76e-05
  pruner_type: base
  scheduler: true
  warmup: 0.1
  weight_decay: 0.000132
  feat_loss: cwd
  reset: false
  temperature: 4.75
  prune_rate: 0.5
  momentum: 0.8
  kd_lr: 0.000664
  kd_weight_decay: 3.77e-05
  lamb: 0.5
  alpha: 5.0
  kd_warmup: 0.1
  kd_scheduler: true
  kd_T_0: 90.0
  label_smoothing: 0.05

gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 256
  norm: layer
  num_layers: 6
  residual: true
  T_0: null
  imp_type: fpgm
  isomorphic: true
  lr: 0.00836
  prune_T_0: null
  prune_lr: 0.00284
  prune_scheduler: false
  prune_step: 1
  prune_warmup: 0.0
  prune_weight_decay: 6.97e-05
  pruner_type: base
  scheduler: false
  warmup: 0.0
  weight_decay: 0.000147
  feat_loss: mse
  reset: true
  temperature: null
  prune_rate: 0.5
  momentum: 0.99
  kd_lr: 0.00056
  kd_weight_decay: 6.87e-05
  lamb: 1.25
  alpha: 1.75
  kd_warmup: 0.05
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.15
