seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 256
  dropout: 0.7
  num_layers: 2
  norm: layer
  residual: false
  T_0: null
  imp_type: fpgm
  isomorphic: false
  lr: 0.00452
  prune_T_0: 120.0
  prune_lr: 0.006
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.0
  prune_weight_decay: 0.0329
  pruner_type: bnscale
  scheduler: false
  warmup: 0.15
  weight_decay: 8.49e-05
  feat_loss: mse
  reset: false
  temperature: null
  prune_rate: 0.5
  momentum: 0.8
  kd_lr: 0.00941
  kd_weight_decay: 2.48e-05
  lamb: 3.5
  alpha: 0.25
  kd_warmup: 0.0
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.3

gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 256
  norm: layer
  num_layers: 3
  residual: false
  T_0: null
  imp_type: fpgm
  isomorphic: true
  lr: 0.00103
  prune_T_0: 120.0
  prune_lr: 1.17e-05
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.1
  prune_weight_decay: 2.14e-05
  pruner_type: group
  scheduler: false
  warmup: 0.15
  weight_decay: 7.72e-05
  feat_loss: cwd
  reset: true
  temperature: 2.75
  prune_rate: 0.5
  momentum: 0.9
  kd_lr: 0.00809
  kd_weight_decay: 2.9e-05
  lamb: 1.25
  alpha: 3.0
  kd_warmup: 0.0
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.25
