seed: 42
dataset:
    split: fixed
gcn:
    dropout: 0.5
    epochs: 1000
    hidden: 512
    norm: layer
    num_layers: 3
    residual: false
    0.5:
        T_0: 90.0
        imp_type: group
        isomorphic: true
        lr: 0.000395
        prune_T_0: 120.0
        prune_lr: 0.00268
        prune_scheduler: true
        prune_step: 3
        prune_warmup: 0.1
        prune_weight_decay: 0.000603
        pruner_type: base
        scheduler: true
        warmup: 0.0
        weight_decay: 5.45e-05
    0.6:
        T_0: 30.0
        imp_type: group
        isomorphic: false
        lr: 0.000512
        prune_T_0: .nan
        prune_lr: 0.00128
        prune_scheduler: false
        prune_step: 3
        prune_warmup: 0.0
        prune_weight_decay: 0.000446
        pruner_type: group
        scheduler: true
        warmup: 0.0
        weight_decay: 0.000206
    0.7:
        T_0: 90.0
        imp_type: fpgm
        isomorphic: true
        lr: 0.000462
        prune_T_0: 60.0
        prune_lr: 0.00307
        prune_scheduler: true
        prune_step: 1
        prune_warmup: 0.1
        prune_weight_decay: 0.096
        pruner_type: base
        scheduler: true
        warmup: 0.15
        weight_decay: 5.45e-05
sage:
    epochs: 1000
    hidden: 64
    dropout: 0.3
    num_layers: 4
    norm: layer
    residual: false
    0.5:
        T_0: .nan
        imp_type: group
        isomorphic: false
        lr: 0.000606
        prune_T_0: 60.0
        prune_lr: 0.000226
        prune_scheduler: true
        prune_step: 2
        prune_warmup: 0.15
        prune_weight_decay: 0.0013
        pruner_type: group
        scheduler: false
        warmup: 0.05
        weight_decay: 5.4e-05
    0.6:
        T_0: .nan
        imp_type: lamp
        isomorphic: true
        lr: 0.00337
        prune_T_0: 60.0
        prune_lr: 0.00136
        prune_scheduler: true
        prune_step: 2
        prune_warmup: 0.05
        prune_weight_decay: 0.00052
        pruner_type: group
        scheduler: false
        warmup: 0.1
        weight_decay: 0.00022
    0.7:
        T_0: .nan
        imp_type: group
        isomorphic: true
        lr: 0.00321
        prune_T_0: 150.0
        prune_lr: 0.000546
        prune_scheduler: true
        prune_step: 2
        prune_warmup: 0.15
        prune_weight_decay: 0.00108
        pruner_type: bnscale
        scheduler: false
        warmup: 0.1
        weight_decay: 0.000112
gin:
    dropout: 0.6
    epochs: 1000
    hidden: 256
    lr: 0.001
    norm: layer
    num_layers: 2
    residual: false
    weight_decay: 5e-4
cheb:
    K: 3
    dropout: 0.8
    epochs: 1000
    hidden: 256
    lr: 0.001
    norm: null
    num_layers: 3
    residual: true
    weight_decay: 5e-4
