seed: 123
dataset:
  split: class
  label_num_per_class: 20
  valid_num: 500
  test_num: 1000

sgformer:
    epochs: 1000
    backbone: gcn
    hidden: 64
    dropout: 0.5
    num_layers: 3
    lr: 0.01
    weight_decay: 5e-5

    graph_weight: 0.8
    ours_dropout: 0.2


