

core:
    logger:
        log_dir: "log"
        log_level: "INFO"
        log_format: "%(asctime)s - %(name)s - [%(levelname)s]: %(message)s"
        date_format: "%Y-%m-%d %H:%M:%S"

    parser:
        seed: 42


dataset:
    utils:
        dir: "raw_data"


imputer:
    feature_propagation_imputer:
        num_iterations: 40

    simple_imputer:
        fix_value: 0


model:
    module:
        num_layers: 2
        dropout: 0.5

    sandbox:
        number_node: 128
        number_edge: 1000
        number_iterations: 1000

    utils:
        activation: relu
        normalize: identity
