seed: 42
dataset:
  split: fixed

gcn:
    epochs: 1500
    hidden: 64
    dropout: 0.3
    num_layers: 2
    lr: 0.001
    weight_decay: 5e-4
    norm: layer
    residual: True

sage:
    epochs: 1500
    hidden: 64
    dropout: 0.7
    num_layers: 2
    lr: 0.001
    weight_decay: 5e-4
    norm: batch
    residual: True

gin:
    epochs: 1500
    hidden: 64
    dropout: 0.4
    num_layers: 1
    lr: 0.001
    weight_decay: 5e-4
    norm: layer
    residual: True

