seed: 123
dataset:
  label_num_per_class: 20
  split: class
  test_num: 1000
  valid_num: 500
sage:
  epochs: 500
  hidden: 512
  dropout: 0.2
  num_layers: 3
  norm: null
  residual: false
  T_0: null
  imp_type: lamp
  isomorphic: true
  lr: 0.00492
  prune_T_0: 120.0
  prune_lr: 0.0022
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.05
  prune_weight_decay: 0.00127
  pruner_type: bnscale
  scheduler: false
  warmup: 0.05
  weight_decay: 0.139
  reset: true
  prune_rate: 0.7
  momentum: 0.8
  kd_lr: 0.000159
  kd_weight_decay: 0.0016
  lamb: 0.9
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.3
gin:
  dropout: 0.7
  epochs: 500
  hidden: 256
  lr: 0.001
  norm: null
  num_layers: 2
  residual: true
  weight_decay: 5e-4
cheb:
  K: 3
  dropout: 0.7
  epochs: 500
  hidden: 512
  lr: 0.001
  norm: null
  num_layers: 2
  residual: true
  weight_decay: 5e-4
gcn:
  dropout: 0.5
  epochs: 500
  hidden: 512
  norm: null
  num_layers: 2
  residual: false
  T_0: 60.0
  imp_type: group
  isomorphic: true
  lr: 0.00285
  prune_T_0: null
  prune_lr: 0.000119
  prune_scheduler: false
  prune_step: 1
  prune_warmup: 0.05
  prune_weight_decay: 0.000163
  pruner_type: base
  scheduler: true
  warmup: 0.0
  weight_decay: 0.00774
  reset: false
  prune_rate: 0.5
  momentum: 0.8
  kd_lr: 0.000368
  kd_weight_decay: 0.000968
  lamb: 0.7
  kd_warmup: 0.05
  kd_scheduler: true
  kd_T_0: 120.0
  label_smoothing: 0.2
