seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 64
  dropout: 0.3
  num_layers: 4
  norm: layer
  residual: false
  T_0: null
  imp_type: group
  isomorphic: false
  lr: 0.000606
  prune_T_0: 60.0
  prune_lr: 0.000226
  prune_scheduler: true
  prune_step: 2
  prune_warmup: 0.15
  prune_weight_decay: 0.0013
  pruner_type: group
  scheduler: false
  warmup: 0.05
  weight_decay: 5.4e-05
  reset: false
  prune_rate: 0.5
  momentum: 0.9
  kd_lr: 0.00339
  kd_weight_decay: 2.08e-05
  lamb: 0.8
  kd_warmup: 0.1
  kd_scheduler: true
  kd_T_0: 30.0
  label_smoothing: 0.15
gin:
  dropout: 0.6
  epochs: 1000
  hidden: 256
  lr: 0.001
  norm: layer
  num_layers: 2
  residual: false
  weight_decay: 5e-4
cheb:
  K: 3
  dropout: 0.8
  epochs: 1000
  hidden: 256
  lr: 0.001
  norm: null
  num_layers: 3
  residual: true
  weight_decay: 5e-4
gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 512
  norm: layer
  num_layers: 3
  residual: false
  T_0: 30.0
  imp_type: group
  isomorphic: false
  lr: 0.000512
  prune_T_0: null
  prune_lr: 0.00128
  prune_scheduler: false
  prune_step: 3
  prune_warmup: 0.0
  prune_weight_decay: 0.000446
  pruner_type: group
  scheduler: true
  warmup: 0.0
  weight_decay: 0.000206
  reset: false
  prune_rate: 0.6
  momentum: 0.99
  kd_lr: 0.000605
  kd_weight_decay: 2.67e-05
  lamb: 0.6
  kd_warmup: 0.1
  kd_scheduler: true
  kd_T_0: 150.0
  label_smoothing: 0.0
