seed: 123
dataset:
  label_num_per_class: 20
  split: class
  test_num: 1000
  valid_num: 500
sage:
  epochs: 500
  hidden: 256
  dropout: 0.7
  num_layers: 3
  norm: null
  residual: false
  T_0: 120.0
  imp_type: group
  isomorphic: true
  lr: 0.0018
  prune_T_0: 60.0
  prune_lr: 0.000146
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.15
  prune_weight_decay: 0.277
  pruner_type: bnscale
  scheduler: true
  warmup: 0.1
  weight_decay: 0.00674
  reset: true
  prune_rate: 0.5
  momentum: 0.995
  kd_lr: 0.000425
  kd_weight_decay: 0.000415
  lamb: 0.7
  kd_warmup: 0.05
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.1
gin:
  dropout: 0.4
  epochs: 500
  hidden: 512
  lr: 0.001
  norm: null
  num_layers: 2
  residual: true
  weight_decay: 5e-4
cheb:
  K: 3
  dropout: 0.6
  epochs: 500
  hidden: 256
  lr: 0.001
  norm: null
  num_layers: 3
  residual: true
  weight_decay: 5e-4
gcn:
  dropout: 0.7
  epochs: 500
  hidden: 512
  norm: null
  num_layers: 3
  residual: false
  T_0: 60.0
  imp_type: group
  isomorphic: false
  lr: 0.0038
  prune_T_0: 30.0
  prune_lr: 0.00055
  prune_scheduler: true
  prune_step: 2.0
  prune_warmup: 0.1
  prune_weight_decay: 2.37e-05
  pruner_type: group
  scheduler: true
  warmup: 0.05
  weight_decay: 8.2e-05
  reset: false
  prune_rate: 0.6
  momentum: 0.8
  kd_lr: 0.00143
  kd_weight_decay: 0.0296
  lamb: 0.5
  kd_warmup: 0.15
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.15
