seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 64
  dropout: 0.2
  num_layers: 6
  norm: layer
  residual: true
  T_0: null
  imp_type: group
  isomorphic: true
  lr: 0.00231
  prune_T_0: null
  prune_lr: 0.000116
  prune_scheduler: false
  prune_step: 2
  prune_warmup: 0.0
  prune_weight_decay: 0.000128
  pruner_type: base
  scheduler: false
  warmup: 0.15
  weight_decay: 0.00033
  reset: true
  prune_rate: 0.6
  momentum: 0.995
  kd_lr: 0.00133
  kd_weight_decay: 3.39e-05
  lamb: 0.7
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.05
gin:
  dropout: 0.3
  epochs: 1000
  hidden: 256
  lr: 0.001
  norm: layer
  num_layers: 2
  residual: false
  weight_decay: 5e-5
cheb:
  K: 3
  dropout: 0.8
  epochs: 1500
  hidden: 512
  lr: 0.001
  norm: layer
  num_layers: 2
  residual: false
  weight_decay: 5e-4
gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 256
  norm: layer
  num_layers: 6
  residual: true
  T_0: null
  imp_type: fpgm
  isomorphic: true
  lr: 0.00836
  prune_T_0: null
  prune_lr: 0.00284
  prune_scheduler: false
  prune_step: 1
  prune_warmup: 0.0
  prune_weight_decay: 6.97e-05
  pruner_type: base
  scheduler: false
  warmup: 0.0
  weight_decay: 0.000147
  reset: false
  prune_rate: 0.5
  momentum: 0.8
  kd_lr: 0.000437
  kd_weight_decay: 2.05e-05
  lamb: 0.6
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.25
