seed: 42
dataset:
  split: fixed
sage:
  epochs: 1500
  hidden: 64
  dropout: 0.7
  num_layers: 2
  norm: batch
  residual: true
  T_0: null
  imp_type: group
  isomorphic: true
  lr: 0.00889
  prune_T_0: null
  prune_lr: 2.63e-05
  prune_scheduler: false
  prune_step: 3
  prune_warmup: 0.15
  prune_weight_decay: 0.891
  pruner_type: base
  scheduler: false
  warmup: 0.1
  weight_decay: 0.00811
  reset: false
  prune_rate: 0.5
  momentum: 0.995
  kd_lr: 0.000478
  kd_weight_decay: 0.000352
  lamb: 0.5
  kd_warmup: 0.0
  kd_scheduler: true
  kd_T_0: 150.0
  label_smoothing: 0.3
gin:
  dropout: 0.4
  epochs: 1500
  hidden: 64
  lr: 0.001
  norm: layer
  num_layers: 1
  residual: true
  weight_decay: 5e-4
gcn:
  dropout: 0.3
  epochs: 1500
  hidden: 64
  norm: layer
  num_layers: 2
  residual: true
  T_0: null
  imp_type: fpgm
  isomorphic: true
  lr: 0.00223
  prune_T_0: 120.0
  prune_lr: 0.00114
  prune_scheduler: true
  prune_step: 1
  prune_warmup: 0.0
  prune_weight_decay: 0.000311
  pruner_type: bnscale
  scheduler: false
  warmup: 0.0
  weight_decay: 0.000852
  reset: false
  prune_rate: 0.5
  momentum: 0.995
  kd_lr: 0.000389
  kd_weight_decay: 0.00292
  lamb: 0.4
  kd_warmup: 0.15
  kd_scheduler: true
  kd_T_0: 60.0
  label_smoothing: 0.3
