seed: 42
dataset:
  split: fixed
sage:
  epochs: 1000
  hidden: 256
  dropout: 0.7
  num_layers: 2
  norm: layer
  residual: false
  T_0: null
  imp_type: fpgm
  isomorphic: false
  lr: 0.00452
  prune_T_0: 120.0
  prune_lr: 0.006
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.0
  prune_weight_decay: 0.0329
  pruner_type: bnscale
  scheduler: false
  warmup: 0.15
  weight_decay: 8.49e-05
  reset: true
  prune_rate: 0.5
  momentum: 0.995
  kd_lr: 0.00117
  kd_weight_decay: 0.000103
  lamb: 0.9
  kd_warmup: 0.1
  kd_scheduler: false
  kd_T_0: null
  label_smoothing: 0.2
gin:
  dropout: 0.6
  epochs: 1000
  hidden: 256
  lr: 0.001
  norm: layer
  num_layers: 2
  residual: true
  weight_decay: 0.0
gcn:
  dropout: 0.5
  epochs: 1000
  hidden: 256
  norm: layer
  num_layers: 3
  residual: false
  T_0: null
  imp_type: fpgm
  isomorphic: true
  lr: 0.00103
  prune_T_0: 120.0
  prune_lr: 1.17e-05
  prune_scheduler: true
  prune_step: 3
  prune_warmup: 0.1
  prune_weight_decay: 2.14e-05
  pruner_type: group
  scheduler: false
  warmup: 0.15
  weight_decay: 7.72e-05
  reset: false
  prune_rate: 0.5
  momentum: 0.8
  kd_lr: 0.00144
  kd_weight_decay: 0.000103
  lamb: 0.9
  kd_warmup: 0.0
  kd_scheduler: true
  kd_T_0: 30.0
  label_smoothing: 0.15
